export const primary = "red.400"
export const lightPrimary = "red.50"
export const darkPrimary = "red.600"
export const secondary = "yellow.100"
export const lightSecondary = "yellow.50"
export const darkSecondary = "yellow.500"